

# https://stackoverflow.com/questions/3931741/why-does-make-think-the-target-is-up-to-date
# To force rebuild on these kind of not-file-related targets, you should make them phony as follows:
.PHONY: parsing-positionals

# Top 3 most deadliest cancers according to: https://www.cancer.gov/types/common-cancers
parsing-positionals:
	./parsing-positionals 'lung (including bronchus)' breast 'colon and rectal'

parsing-positionals-shift:
	./parsing-positionals 'lung (including bronchus)' breast 'colon and rectal'
